Fixing and adding more Norwegian oils
NOAA-ORR-ERD/noaa-oil-data pull request #3
Opened 2023-12-13 16:12 UTC by knutfrode

All Norwegian oils are now `gnome_suitable`, after changing `fraction_recovered` `max_value` to `value`.
Added missing cuts to two oils, and added four new oils.

2024-06-28 22:16 UTC, ChrisBarker-NOAA requested changes
A few issues -- highlighted above, and when I run the validation, I get:

`/Users/chris.barker/Hazmat/GitLab/noaa-oil-data/data/oil/NO`

**Generated:** Jun 28, 2024 - 14:00


#### `NO00022`: ELLI SOUTH

E062: Viscosity data is not strictly decreasing


#### `NO00104`: VISUND

E062: Viscosity data is not strictly decreasing

W100: Not GNOME compatible: Viscosities must be decreasing with temperature


#### `NO00109`: SVALIN

E060: Oil fraction in distillation cuts is not accumulative

I haven't looked carefully at what the issues are myself.
NOTE: you can run the validation yourself, with the adiso_db library -- it isntalls a command line utility:

adios_db_validate [dir_with_data]

and it will generate two reports:

validation_by_record.md

validation_by_error.md

same information, just in different order

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00159.json
> +            ]
What is this? bulk composition needs a name and a measurment, such as:

```
                {
                    "name": "wax_content",
                    "measurement": {
                        "value": 0.0788,
                        "unit": "fraction",
                        "unit_type": "massfraction"
                    }
                },
```

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00160.json
> +            ]
same as 159 -- what is this?

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00162.json
> +                }
and here.

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00163.json
> +            "bulk_composition": [
and here.

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00164.json
> +            "bulk_composition": [
and here...

2024-06-28 22:16 UTC, ChrisBarker-NOAA commented on data/oil/NO/NO00159.json
> +        "product_type": "crude oil nos",
This should be "Crude Oil NOS" -- case sensitive.

2024-11-07 14:14 UTC, knutfrode commented on data/oil/NO/NO00159.json
> +        "product_type": "crude oil nos",
This is fixed in [8f4c482](https://github.com/NOAA-ORR-ERD/noaa-oil-data/pull/3/commits/8f4c4822d95693e1573065005e8ed1650d2a1c3e)

2024-11-07 14:14 UTC, knutfrode commented on data/oil/NO/NO00164.json
> +            "bulk_composition": [
These are also fixed in [8f4c482](https://github.com/NOAA-ORR-ERD/noaa-oil-data/pull/3/commits/8f4c4822d95693e1573065005e8ed1650d2a1c3e)

2024-11-08 14:23 UTC, knutfrode commented
@ChrisBarker-NOAA 
I believe I have now fixed all these errors, so that these oils should all be gnome compatible.

2024-11-13 15:55 UTC, knutfrode commented
For me this PR is now ready to merge, and I believe the requested changes are fulfilled.

2024-11-13 18:22 UTC, ChrisBarker-NOAA commented
Thanks! I'll try to get this merged in soon -- it's a bit tricky, as the "official" version is on an internal git instance, but I'll work it out.

2024-11-14 22:36 UTC, ChrisBarker-NOAA commented
I had a chance to take a look -- there are still some issues -- we added some more validation recently.

[validation_by_error.md](https://github.com/user-attachments/files/17758645/validation_by_error.md)

```
#### `NO00150 (NO00150)` -- SF NORD BRENT:

Duplicate sub_sample name(s): ['16.0% Evaporated', '28.8% Evaporated', '38.7% Evaporated'] names must be unique
```
This one looks to me, at a glance, like the data somehow got split up between two subsamples.

```
## E062: (5 records affected)

#### `NO00022 (NO00022)` -- ELLI SOUTH:

Viscosity data is not strictly decreasing
```
this on is checking if the viscosity goes down as the temperature goes up -- which it should.

If it doesn't it means one of
- an error / typo
- viscosity was measured by two different labs / different methods
- viscosity was measured at different shear rates
   - if that's the case, the shear rate can be specified, if you know what it is, and teh code will work it out.

2024-11-21 18:06 UTC, closed without merging